const info = {
  name: "Arsham Ramzani",
  home: "HOME",
  about: "ABOUT",
  resume: "RESUME",
  portfolios: "PORTFOLIO",
  contact: "CONTACT",
  hi1: "Hi, I am ",
  hi2: "",
  homeDesc:
    "I am a frontend web developer and getting ready for being a fullstack developer as soon as possible",
  aboutMe: "ABOUT ME",
  fullName: "Full Name",
  age: "Age",
  nationality: "Nationality",
  languages: "Languages",
  phone: "Phone",
  years: "years",
  iranian: "Iranian",
  persian: "Persian",
  english: "English",
  german: "German",
  services: "Services",
  downloadcv: "download CV",
  webDesign: "Web Design",
  webDevelopment: "Web Development",
  mobileApplication: "Mobile Application",
  designDesc:
    "Implementing user interfaces with React, React Router, and Material UI, CSS, JSS, and Bootstrap for styling. Creating responsive websites",
  developDesc:
    "I like Nodejs and enjoing coding with that and building a web site with it , it's fun ;)",
  mobileAppDesc:
    "I developed an aplication with React Native (Really i love it , it veryyyyy fun and i get more hope when i work with it) for an university appliction",
  mySkills: "My Skills",
  html5: "HTML5",
  css3: "CSS3",
  js: "JavaScript",
  reactNative: "React Native",
  reactJS: "React js",
  bootstrap: "Bootstrap",
  materialUI: "MaterialUI",
  nodeJs: "Node JS",
  workExperience: "Work Experience",
  boardgamePresenter: "Board Game Presenter",
  frontendDeveloper: "Frontend Developer",
  jobFirstYear: "2020 - 2021",
  jobFirstTitle: "Windows app developer",
  jobFirstCompany: "Ghalamchi",
  jobFirstDesc:
    "Program an app for contorl and better view of student for managing them",
  jobSecondYear: "2021 - now",
  jobSecondTitle: "Frontend Developer",
  jobSecondCompany: "Adl Afarinan Mandegar co.",
  jobSecondDesc:
    "Frontend developer at Adl Afarinan Mandegar , and some design work ;)",
  educationalQualification: "Educational Qualification",
  firstDegreeYear: "2012 - 2018",
  firstDegree: "High School Diploma (Theoretical and Mathematical Physics)",
  firstSchoolName:
    "National Organization for Development of Exceptional Talents (Sampad)",
  firstLocation: "Iran , Tehran",
  secondDegreeYear: "2019 - 2023",
  secondDegree: "Bachelor's degree (Computer Engineering)",
  secondSchoolName: "Kharazmi University",
  secondLocation: "Iran , Karaj",
  contactMe: "Contact Me",
  getInTouch: "Get In Touch",
  enterYourName: "Enter your name",
  enterYourEmail: "Enter your Email",
  enterYourSubject: "Enter your subject",
  enterYourMessage: "Enter your message",
  email: "Email",
  address: "Address",
  send: "Send Massage",
  emailAddress: "arsham.ramezani@gmail.com",
  addressDesc: "Iran, Tehran",
  messageSent: "Your message has been sent successfully",
};
export default info;
