const info = {
  name: 'AmirShayan Mobaraki',
  home: 'HOME',
  about: 'ABOUT',
  resume: 'RESUME',
  portfolios: 'PORTFOLIO',
  contact: 'CONTACT',
  hi1: 'Hi, I am ',
  hi2: '',
  homeDesc: 'I am a fullstack developer',
  aboutMe: 'ABOUT ME',
  fullName: 'Full Name',
  age: 'Age',
  nationality: 'Nationality',
  languages: 'Languages',
  phone: 'Phone',
  years: 'years',
  iranian: 'Iranian',
  persian: 'Persian',
  english: 'English',
  german: 'German',
  services: 'Services',
  downloadcv: 'download CV',
  webDesign: 'Web Design',
  webDevelopment: 'Web Development',
  mobileApplication: 'Mobile Application',
  designDesc:
    'Implementing user interfaces with React, React Router, and Material UI, CSS, JSS, Tailwind, Styled Component and Bootstrap for styling. Creating responsive websites',
  developDesc:
    "I like Nodejs and enjoing coding with that and building a web site with it , it's fun ;)",
  mobileAppDesc:
    'I developed an aplication with React Native (Really i love it , it veryyyyy fun and i get more hope when i work with it) for an university appliction',
  mySkills: 'My Skills',
  html5: 'HTML5',
  css3: 'CSS3',
  js: 'JavaScript',
  reactNative: 'React Native',
  reactJS: 'React js',
  nextJs: 'Nextjs',
  tailwind: 'Tailwind',
  apollo: 'Apollo',
  graphql: 'Graphql',
  bootstrap: 'Bootstrap',
  materialUI: 'MaterialUI',
  nodeJs: 'Node JS',
  workExperience: 'Work Experience',
  boardgamePresenter: 'Board Game Presenter',
  frontendDeveloper: 'Frontend Developer',
  jobFirstYear: '2020 - 2021',
  jobFirstTitle: 'Windows app developer',
  jobFirstCompany: 'Ghalamchi',
  jobFirstDesc:
    'Program an app for contorl and better view of student for managing them',
  jobSecondYear: '2021 - 2022',
  jobSecondTitle: 'Frontend Developer',
  jobSecondCompany: 'Adl Afarinan Mandegar co.',
  jobSecondDesc:
    'Frontend developer at Adl Afarinan Mandegar , and some design work ;)',
  jobThirdYear: '2022 - 2023',
  jobThirdTitle: 'FullStack Developer',
  jobThirdCompany: 'Nodemon',
  jobThirdDesc: 'FullStack developer at Nodemon and some Devops tasks :)',
  educationalQualification: 'Educational Qualification',
  firstDegreeYear: '2012 - 2018',
  firstDegree: 'High School Diploma (Theoretical and Mathematical Physics)',
  firstSchoolName:
    'National Organization for Development of Exceptional Talents (Sampad)',
  firstLocation: 'Iran , Tehran',
  secondDegreeYear: '2019 - 2023',
  secondDegree: "Bachelor's degree (Computer Engineering)",
  secondSchoolName: 'Kharazmi University',
  secondLocation: 'Iran , Karaj',
  contactMe: 'Contact Me',
  getInTouch: 'Get In Touch',
  enterYourName: 'Enter your name',
  enterYourEmail: 'Enter your Email',
  enterYourSubject: 'Enter your subject',
  enterYourMessage: 'Enter your message',
  email: 'Email',
  address: 'Address',
  send: 'Send Massage',
  emailAddress: ['AmirShayan1999@gmail.com'],
  addressDesc: 'Iran, Tehran',
  messageSent: 'Your message has been sent successfully',
  phoneNumbers: ['(98)9127928451', '(98)9213988212']
}
export default info
