const info = {
  name: 'آرشام رمضانی',
  home: 'خانه',
  about: 'درباره من',
  resume: 'رزومه',
  portfolios: 'پورتفولیو',
  contact: 'ارتباط با من',
  hi1: 'سلام من ',
  hi2: ' هستم',
  homeDesc: 'من یک توسعه دهنده ی فول استک هستم',
  aboutMe: 'معرفی',
  fullName: 'نام کامل',
  age: 'سال',
  nationality: 'ملیت',
  languages: 'زبان\u200cها',
  phone: 'تلفن',
  years: 'سال',
  iranian: 'ایرانی',
  persian: 'فارسی',
  english: 'انگلیسی',
  german: 'آلمانی',
  services: 'خدمات',
  downloadcv: 'دانلود رزومه',
  webDesign: 'طراحی وب',
  webDevelopment: 'توسعه وب',
  mobileApplication: 'اپلیکیشن موبایل',
  designDesc:
    'یه سری چیزا با ری اکت می زنم با کمک دوست عزیزم متریال که کارمو خیلی راحت می کنه :)',
  developDesc:
    'یکم node js دوست دارم و وقتی باهاش کد می زنم لذت می برم , مخصوصا وقتی که باهاش سایت می زنم:)',
  mobileAppDesc:
    'با react native اپلیکیشن می سازم راستش خیلی خیلی دوسش دارم و وقتی کد می زنم یه حس خیلی بهتری دارم و کلی روحیه می گیرم برای اینده',
  mySkills: 'مهارت\u200cها',
  html5: 'HTML5',
  css3: 'CSS3',
  js: 'JavaScript',
  reactNative: 'React Native',
  reactJS: 'React js',
  nextJs: 'Nextjs',
  tailwind: 'Tailwind',
  apollo: 'Apollo',
  graphql: 'Graphql',
  bootstrap: 'Bootstrap',
  materialUI: 'MaterialUI',
  nodeJs: 'Node JS',
  workExperience: 'تجربه\u200cهای کاری',
  boardgamePresenter: 'گیم مستر',
  frontendDeveloper: 'توسعه\u200cدهنده سمت کاربر',
  jobFirstYear: '1399 - 1400',
  jobFirstTitle: 'توسعه دهنده ی برنامه ویندوز',
  jobFirstCompany: 'قلم چی',
  jobFirstDesc:
    'طراحی یک برنامه برای کنترل و دید بهتر به دانش آموزان برای مدیریت انها',
  jobSecondYear: '1400 - 1401',
  jobSecondTitle: 'توسعه دهنده سمت کاربر',
  jobSecondCompany: 'شرکت عدل آفرینان ماندگار',
  jobSecondDesc:
    'توسعه دهنده ی سمت کاربر در شرکت عدل افرینان ماندگار و همچنین یکم کم کار طراحی',
  jobThirdYear: '1402 - 1403',
  jobThirdTitle: 'توسعه دهنده سمت کاربر و سرور',
  jobThirdCompany: 'Nodemon',
  jobThirdDesc: 'توسعه دهنده سمت کاربر و سرور و مقادی هم کار Devops',
  educationalQualification: 'سوابق تحصیلی',
  firstDegreeYear: '1392 - 1398',
  firstDegree: 'دیپلم رشته ریاضی و فیزیک',
  firstSchoolName: 'مدرسه میرزاکوچکخان (سمپاد)',
  firstLocation: 'ایران، تهران',
  secondDegreeYear: '1398 - 1402',
  secondDegree: 'کارشناسی مهندسی کامپیوتر',
  secondSchoolName: 'دانشگاه خوارزمی',
  secondLocation: 'ایران، کرج',
  contactMe: 'اطلاعات تماس',
  getInTouch: 'پیام بدهید',
  enterYourName: 'نام',
  enterYourEmail: 'ایمیل',
  enterYourSubject: 'موضوع پیام',
  enterYourMessage: 'متن پیام',
  email: 'ایمیل',
  address: 'آدرس',
  send: 'ارسال پیام',
  emailAddress: ['arsham.ramezani@gmail.com'],
  addressDesc: 'ایران, تهران',
  messageSent: 'پیام شما ارسال شد',
  phoneNumbers: ['۹۱۱۵۶۴۷۴۳۲(۹۸)', '۹۳۵۷۹۹۵۹۲۹(۹۸)']
}
export default info
